services:
  felis.broker.console:
    image: ${DOCKER_REGISTRY-}felisbrokerconsole
    build:
      context: .
      dockerfile: Examples/Felis.Broker.Console/Dockerfile
    ports:
      - "7110:7110"

  felis.publisher.net.console:
    image: ${DOCKER_REGISTRY-}felispublishernetconsole
    build:
      context: .
      dockerfile: Examples/Felis.Publisher.Net.Console/Dockerfile

  felis.publisher.ttl.net.console:
    image: ${DOCKER_REGISTRY-}felispublisherttlnetconsole
    build:
      context: .
      dockerfile: Examples/Felis.Publisher.Ttl.Net.Console/Dockerfile

  felis.subscriber.net.console:
    image: ${DOCKER_REGISTRY-}felissubscribernetconsole
    build:
      context: .
      dockerfile: Examples/Felis.Subscriber.Net.Console/Dockerfile

  felis.subscriber.noack.net.console:
    image: ${DOCKER_REGISTRY-}felissubscribernoacknetconsole
    build:
      context: .
      dockerfile: Examples/Felis.Subscriber.NoAck.Net.Console/Dockerfile
