services:
  felis.broker.console:
    image: ${DOCKER_REGISTRY-}felisbrokerconsole
    build:
      context: .
      dockerfile: Examples/Felis.Broker.Console/Dockerfile
    ports:
      - "7110:7110"
    environment:
      - ASPNETCORE_URLS=https://+:7110;http://+:5000


  felis.publisher.console:
    image: ${DOCKER_REGISTRY-}felispublisherconsole
    build:
      context: .
      dockerfile: Examples/Felis.Publisher.Console/Dockerfile
    depends_on:
      - felis.broker.console

  felis.subscriber.console:
    image: ${DOCKER_REGISTRY-}felissubscriberconsole
    build:
      context: .
      dockerfile: Examples/Felis.Subscriber.Console/Dockerfile
    depends_on:
      - felis.broker.console
