services:
  felis.broker.console:
    image: ${DOCKER_REGISTRY-}felisbrokerconsole
    build:
      context: .
      dockerfile: Examples/Felis.Broker.Console/Dockerfile
    ports:
      - "7110:7110"
    environment:
      - ASPNETCORE_URLS=https://+:7110;http://+:5000


  felis.publisher.node.console:
    image: ${DOCKER_REGISTRY-}felispublishernodeconsole
    build:
      context: .
      dockerfile: Examples/Felis.Publisher.Node.Console/Dockerfile
    depends_on:
      - felis.broker.console

  felis.subscriber.node.console:
    image: ${DOCKER_REGISTRY-}felissubscribernodeconsole
    build:
      context: .
      dockerfile: Examples/Felis.Subscriber.Node.Console/Dockerfile
    depends_on:
      - felis.broker.console
