version: "3.8"
services:
  felis_broker_console:
    image: felisbrokerconsole:latest
    build:
      context: .
      dockerfile: Examples/Felis.Broker.Console/Dockerfile
    ports:
      - "7110:7110"
    environment:
      - BROKER_PORT=7110
      - ASPNETCORE_URLS=https://+:${BROKER_PORT}
      - ASPNETCORE_ENVIRONMENT=Production # Adjust as needed
      - BROKER_CERTIFICATE_NAME=Output.pfx
      - BROKER_CERTIFICATE_PASSWORD=Password.1

  felis_publisher_console:
    image: felispublisherconsole:latest
    build:
      context: .
      dockerfile: Examples/Felis.Publisher.Console/Dockerfile
    depends_on:
      - felis_broker_console
    environment:
      - BROKER_URL=https://felis_broker_console:7110 

  felis_subscriber_console:
    image: felissubscriberconsole:latest
    build:
      context: .
      dockerfile: Examples/Felis.Subscriber.Console/Dockerfile
    depends_on:
      - felis_broker_console
    environment:
      - BROKER_URL=https://felis_broker_console:7110 

